name: vuejs-static-build

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - run: ls -a

      - uses: actions/checkout@v2

      - run: du -sh ~/.npm
        continue-on-error: true

      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-cache

      - run: du -sh ~/.npm

      - run: npm ci
      - run: du -sh ~/.npm

      - run: npm run build
      - uses: actions/upload-artifact@v2
        with:
          name: static-build
          path: dist
