name: vue static build and push to github pages

on:
  workflow_dispatch:
  push: { branches: [main] }

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: |
          npm ci
          npm run lint
          npm run build
          cd dist
          git init --initial-branch=gh-pages
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A
          git commit -m "$(git -C .. log -1 --format=format:%s)"
          git push -f "https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ GITHUB_REPOSITORY }}"

      # - uses: actions/upload-artifact@v2
      #   with: { name: static-build, path: docs }
