name: vuejs-static-build

on: workflow_dispatch
#  push: { branches: [main] }

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: npm ci && npm run lint && npm run build

      - uses: actions/upload-artifact@v2
        with: { name: static-build, path: dist }
