on: workflow_dispatch
#  push: { branches: [main] }

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with: { path: ~/.npm, key: npm-cache }

      - run: npm ci

      - run: npm run lint

      - run: npm run build

      - uses: actions/upload-artifact@v2
        with: { name: static-build, path: dist }
